---
- name: install required packages
  package:
    name: "{{ item }}"
    state: present
  become: true
  with_items:
    - git

- name: install keys
  include: install_keys.yml
  vars:
    name:         "{{ item.name }}"
    private_key:  "{{ item.private_key }}"
    public_key:   "{{ item.public_key }}"
  with_items:     "{{ deploy_keys }}"
