---
- name: install required packages
  package:
    name: "{{ item }}"
    state: present
  become: true
  with_items:
    - git

- name: "Install user ssh private key"
  no_log: "{{ not deploy_debugging }}"
  copy:
    content: "{{ deploy_private_key }}"
    dest: "{{ deploy_key_full_path }}"
    mode: 0600
    owner: "{{ deploy_user }}"

- name: "Install user ssh public key"
  no_log: "{{ not deploy_debugging }}"
  copy:
    content: "{{ deploy_public_key }}"
    dest: "{{ deploy_key_full_path }}.pub"
    mode: 0644
    owner: "{{ deploy_user }}"
